package scheme

import (
	"TLExtractor/telegram/scheme/types"
	"TLExtractor/utils"
	"fmt"
	"strings"
	"time"
)

func ToString(scheme types.TLSchemeInterface, layer int, withComments bool) string {
	if utils.IsNil(scheme) {
		return ""
	}
	var tl string
	if withComments {
		tl = "///////////////////////////////\n"
		tl += "///////// Main application API\n"
		tl += "///////////////////////////////\n"
		tl += "\n\n// This file is auto-generated by TLExtractor\n"
		tl += fmt.Sprintf("// Copyright (C) %d Laky-64\n", time.Now().Year())
	}
	constructors := scheme.GetConstructors()
	if len(constructors) > 0 {
		tl += "\n\n---types---\n\n"
		tl += toStringObjects(constructors, layer)
	}
	methods := scheme.GetMethods()
	if len(methods) > 0 {
		tl += "\n\n---functions---\n\n"
		tl += toStringObjects(methods, layer)
	}
	if withComments {
		tl += fmt.Sprintf("\n\n// LAYER %d", layer)
	}
	return strings.TrimSpace(tl)
}
