// Code generated by sqlgen. DO NOT EDIT.

package db

import (
    "context"
    "github.com/jackc/pgx/v5/pgxpool"

    "github.com/jackc/pgx/v5"
    "github.com/jackc/pgx/v5/pgconn"
    "github.com/valkey-io/valkey-go"
)

var batchMaxSize = 1000

type DBTX interface {
    Acquire(ctx context.Context) (c *pgxpool.Conn, err error)
    Begin(context.Context) (pgx.Tx, error)
	Exec(context.Context, string, ...interface{}) (pgconn.CommandTag, error)
	Query(context.Context, string, ...interface{}) (pgx.Rows, error)
	QueryRow(context.Context, string, ...interface{}) pgx.Row
}

type DB struct {
    Pool *pgxpool.Pool
{{- range .Queries }}
    {{ . | ToPascalCase }}Store *{{ . | ToPascalCase }}Store
{{- end }}
}

func new(dsn string, redis valkey.Client) (*DB, error) {
    cfg, err := pgxpool.ParseConfig(dsn)
    {{- if gt (len .Enums) 0 }}
    pgxTypes := []string{
        {{- range .Enums }}
        "{{.Name}}",
        "_{{.Name}}",
        {{- end }}
    }
    if err != nil {
        return nil, err
    }
    cfg.AfterConnect = func(ctx context.Context, conn *pgx.Conn) error {
    	for _, pgxType := range pgxTypes {
    		loadType, errLoad := conn.LoadType(context.Background(), pgxType)
    		if errLoad != nil {
    			return err
    		}
    		conn.TypeMap().RegisterType(loadType)
    	}
    	return nil
    }
    {{- end }}
    db, err := pgxpool.NewWithConfig(context.Background(), cfg)
    if err != nil {
        return nil, err
    }
    return &DB{
        Pool: db,
        {{- range .Queries }}
        {{ . | ToPascalCase }}Store: &{{ . | ToPascalCase }}Store{db: db, redis: redis},
        {{- end }}
    }, nil
}