// Code generated by sqlgen. DO NOT EDIT.

package models
{{- if .Imports }}

import (
{{- range .Imports }}
    "{{.}}"
{{- end }}
)
{{- end }}

type {{.Table.Rel.Name | ToPascalCase | Singular}} struct {
    {{- range .Table.Columns }}
    {{.Name | ToPascalCase | ToGoCase}} {{ToGoType . false}} `json:"{{.Name}}{{if not .NotNull}},omitempty{{end}}"`
    {{- end }}
}