// Code generated by sqlgen. DO NOT EDIT.

package models

import (
    "database/sql/driver"
    "encoding/json"
)
{{ range .Enums -}}
{{ $name := .Name | ToPascalCase }}
type {{ $name }} string

const (
    {{- range .Vals }}
    {{ $name }}{{ . | ToPascalCase }} = "{{ . }}"
    {{- end }}
)

func (e *{{ $name }}) Scan(value interface{}) error {
    if value == nil {
        *e = ""
        return nil
    }
    switch s := value.(type) {
	case []byte:
		*e = {{ $name }}(s)
	case string:
		*e = {{ $name }}(s)
	}
    return nil
}

func (e {{ $name }}) Value() (driver.Value, error) {
	if e == "" {
		return nil, nil
	}
	return string(e), nil
}

func (e {{ $name }}) IsNull() bool {
    return e == ""
}

func (src {{ $name }}) MarshalJSON() ([]byte, error) {
	if src.IsNull() {
		return []byte("null"), nil
	}
	return json.Marshal(string(src))
}
{{- end }}